language: java
jdk: oraclejdk8
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: daniel.murygin@gmail.com
  password:
    secure: Nnp9axiq7LVMzHn4IqJ3GzoCU5qj6kv2a6CA54JQRdx49+dPfM3aNJmaT/NhuC7h3Jjs/cA8PKMcd77/N39SMHwevEzot6zAeufHpS75vhEppNHKRshqrAGpCwwKE0vjzQI93DRyOYY/RRMYaj++TGieiXYV+11fQCtBHrOY3JAuU5mnueQA1sd5IrwjXIE9Ub7baD6CWsbuzLvzaoeE+DsMt+ICtIl0MqCGr2qjbBhDd7gO+LLIyrZsa418D9tpMvR0F7YuLovfThy41VtOUMhSyxTIEv50acGorCPf6Z7OHcZuDvJFaNcf5osE8D4yTBK/30siVe2J26yv4dGEuA9wdnsEFKmYMzdrDodrPMEaGWF4HwOpEdNhqfMtGHtjESwuBJy2F77WDNHK+TNbpVH5zH+T0sDoBUydzqgAmRTwAPiJEyG2GCEY0pNb74wzmLQ/kl/O3pYjHvhZtq83BzALO3Y8FQl1H0TZmRWPN+Al91Bx9v7BQKcBVhgs2NxQ62yy87FF61Kg/AfyHU1ca2UKrsbelWay2UjG0AAfbf61cc5sfh3Abpp0j6k2D9Rslpf4QLgHe5Uavh0w1WW3DXYXQl9fQA6uRO3Fa9tuzzvG4NpXniQoyuSxiwwQeBy4YOWTbdSR9LVoa98SfmlJJMY9m2lFbbTsgifWIKvl/V8=
  organization: murygin
  space: development
  on:
    repo: murygin/spring-rest-service
